/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package logger.reconfig.example

import groovy.util.logging.Log4j2

/**
 * Application entry point.
 */
@Log4j2
class App {
    final String greeting = 'Hello world.'

    static void main(String[] args) {
        log.info new App().greeting
    }
}
